name: CI - build native addon and smoke test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install system deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libpcap-dev pkg-config python3 python3-pip ninja-build

      - name: Install system deps (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake libpcap pkg-config ninja

      - name: Install deps
        run: |
          npm ci

      - name: Build native addon
        run: |
          npx cmake-js rebuild --loglevel=info

      - name: Ensure .node filename on Windows
        if: runner.os == 'Windows'
        run: |
          if (Test-Path build\\Release\\soem_addon.dll) { Copy-Item build\\Release\\soem_addon.dll build\\Release\\soem_addon.node -Force }
        shell: pwsh

      - name: Smoke test - require module
        # POSIX smoke test
        if: runner.os != 'Windows'
        run: |
          ls -la build/Release || true
          node -e "try{ const a=require('./build/Release/soem_addon.node'); console.log('exports',Object.keys(a)); const M=a.Master; console.log('Master type',typeof M); const m=new M('lo'); console.log('instantiation ok'); }catch(e){ console.error('smoke test failed', e&&e.message); process.exit(1); }"

      - name: Smoke test - require module (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          if (Test-Path build\\Release\\soem_addon.node) { Write-Output 'found build\\Release\\soem_addon.node' } else { Get-ChildItem build\\Release -Force | Write-Output }
          node -e "try{ const a=require('./build/Release/soem_addon.node'); console.log('exports',Object.keys(a)); const M=a.Master; console.log('Master type',typeof M); const m=new M('lo'); console.log('instantiation ok'); }catch(e){ console.error('smoke test failed', e&&e.message); process.exit(1); }"
